services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel_network

  # Node Service
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: laravel_node
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"  # Ensure Vite is mapped properly
      - "5174:5174"  # If Vite falls back to 5174
    networks:
      - laravel_network
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_APP_URL=${APP_URL}

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8080:80" # Mengubah port dari 80 menjadi 8080
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel_network
    depends_on:
      - app

  # PostgreSQL Service
  db:
    image: postgres:16-alpine
    container_name: laravel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  postgres_data:
